# Generated by Django 5.1.6 on 2025-03-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_icon_linksacc'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservizit',
            name='job',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
