# Generated by Django 5.1.6 on 2025-03-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_uservizit_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=models.ImageField(upload_to='images/icons'),
        ),
        migrations.AlterField(
            model_name='imagespost',
            name='image',
            field=models.ImageField(upload_to='images/images_post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(upload_to='images/preview'),
        ),
        migrations.AlterField(
            model_name='uservizit',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uservizit',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatars'),
        ),
        migrations.AlterField(
            model_name='uservizit',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
