# Generated by Django 5.1.6 on 2025-03-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_icon_image_alter_imagespost_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_post',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
