# Generated by Django 5.1.6 on 2025-03-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_post_date_post_post_is_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linksacc',
            name='icon',
        ),
    ]
