# Generated by Django 5.1.6 on 2025-03-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_linksacc_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksacc',
            name='name',
            field=models.CharField(default='No name', max_length=64),
        ),
    ]
